### ISSUE TITLE
mysql是否需要创建对应的table？

### ISSUE THREAD

**Issue by zxzhang8** [ZJU-ACES-ISE/ChatUniTest#3]
根据readme配置了相关选项，包括Mysql的连接，并且也创建了配置中对应的database，但是在运行run.py时报错如下：
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dyc/Project/ChatUniTest/src/run.py", line 67, in <module>
    run()
  File "/Users/dyc/Project/ChatUniTest/src/run.py", line 29, in run
    drop_table()
  File "/Users/dyc/Project/ChatUniTest/src/database.py", line 174, in drop_table
    db.execute(sql_script)
  File "/Users/dyc/Project/ChatUniTest/src/database.py", line 39, in execute
    self.cursor.execute(script)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 616, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1051 (42S02): Unknown table 'chat_uni_test.class'
```
是否需要创建对应的表？

**Comment by zxzhang8** [comment]
注释掉drop_table解决

**Comment by zxzhang8** [comment]
另外一个问题：在运行后看命令行提示有大约的花费提示，如果参数使用‘gpt-3.5-turbo’还需要费用吗

**Comment by coder-chenzhi** [comment]
@walt676 需要费用，OpenAI的API按使用的token量计费

**Comment by zxzhang8** [comment]
感谢解答
